### ISSUE TITLE
Repo name and binary name

### ISSUE THREAD

**Issue by robgraves** [robgraves/llgdb#1]
Originaly the repo was named llgdb for linked list game data base and then I created a C file gdb.c for game database but realized it would conflict with the GNU debugger gdb so I renamed the file bgdb.c and its binary bgdb for board game data base.

**Comment by robgraves** [comment]
Here I am pretending I'm a developer...sigh.  Tyler, where are you?  I mean, nullist.

**Comment by nullist** [comment]
...

**Comment by robgraves** [comment]
This issue is closed.
